language: ruby
cache: bundler
sudo: false
before_script:
  - psql -c 'create database i18n_sequel_bitemporal;' -U postgres
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.2
  - jruby-9.1.13.0
env:
  - ADAPTER=sqlite3
  - ADAPTER=postgres
gemfile:
  - ci/Gemfile.rails-4.0
  - ci/Gemfile.rails-4.1
  - ci/Gemfile.rails-4.2
  - ci/Gemfile.rails-5.0
  - ci/Gemfile.rails-5.1
matrix:
  allow_failures:
    - rvm: jruby-9.1.13.0
      env: ADAPTER=sqlite3
